services:
  db_test:
    image: postgres:16.3
    container_name: db_test
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - postgresql_db_data_test:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5433:5432

  db_editor_test:
    image: adminer:4.8.1
    container_name: db_editor_test
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 8080
    ports:
      - 8082:8080
    depends_on:
      - db_test


volumes:
  postgresql_db_data_test: